# Generated by Django 4.2.3 on 2024-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cardbank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Banco do cartão",
                "verbose_name_plural": "Bancos do cartão",
                "ordering": ["-id"],
            },
        ),
    ]
