# Generated by Django 4.2.3 on 2024-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gasto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segmento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tipo de comércio"),
                ),
            ],
            options={
                "verbose_name": "Segmento",
                "verbose_name_plural": "Segmentos",
                "ordering": ["-name"],
            },
        ),
    ]
